baseURL = "https://reference.groupdocs.com/tutorials/merger"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-WZTNN8"

[[deployment.targets]]
name = "Production"
URL = "s3://reference.groupdocs.com/?prefix=tutorials/merger/&region=us-west-2"
